[phases.setup]
nixPkgs = ["python311", "gcc", "pango", "gdk-pixbuf", "cairo", "gobject-introspection", "libffi", "zlib", "jpeg", "openjpeg"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = ". .venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT app:app"
