services:
  - type: web
    name: hangarlink-mvp
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      flask db upgrade && gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hangarlink-db
          property: connectionString

databases:
  - name: hangarlink-db
    databaseName: hangarlink
    user: hangarlink
    plan: free
